import json
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import pika
from sqlalchemy import DateTime, Integer, String, Text, create_engine, text
from sqlalchemy.orm import DeclarativeBase, Mapped, Session, mapped_column, sessionmaker

from shared.config import settings
from shared.audit_client import send_audit_event


QUEUE_NAME = "report_jobs"
REPORTS_DIR = Path("/app/reports")


class Base(DeclarativeBase):
    pass


def utc_now() -> datetime:
    return datetime.now(timezone.utc)


class Job(Base):
    __tablename__ = "jobs"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, index=True)
    type: Mapped[str] = mapped_column(String(50), nullable=False)
    status: Mapped[str] = mapped_column(String(20), default="pending", nullable=False, index=True)
    requested_by: Mapped[int | None] = mapped_column(Integer, nullable=True)
    result_path: Mapped[str | None] = mapped_column(String(500), nullable=True)
    error_message: Mapped[str | None] = mapped_column(Text, nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=utc_now, nullable=False)
    completed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)


engine = create_engine(settings.database_url, pool_pre_ping=True)
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)


def rabbitmq_parameters() -> pika.ConnectionParameters:
    credentials = pika.PlainCredentials(settings.rabbitmq_user, settings.rabbitmq_password)
    return pika.ConnectionParameters(
        host=settings.rabbitmq_host,
        port=settings.rabbitmq_port,
        credentials=credentials,
        heartbeat=60,
        blocked_connection_timeout=30,
    )


def connect_with_retry(max_attempts: int = 30, delay_seconds: int = 5) -> pika.BlockingConnection:
    for attempt in range(1, max_attempts + 1):
        try:
            return pika.BlockingConnection(rabbitmq_parameters())
        except pika.exceptions.AMQPConnectionError:
            print(f"RabbitMQ not ready, retrying ({attempt}/{max_attempts})...", flush=True)
            time.sleep(delay_seconds)

    raise RuntimeError("Could not connect to RabbitMQ after retries.")


def load_message(body: bytes) -> dict[str, Any]:
    payload = json.loads(body.decode("utf-8"))
    if not isinstance(payload, dict):
        raise ValueError("Report job message must be an object.")
    if not payload.get("job_id") or payload.get("type") not in {"inventory_report", "low_stock_report"}:
        raise ValueError("Unsupported report job message.")
    return payload


def set_job_failed(db: Session, job_id: int, message: str) -> None:
    job = db.query(Job).filter(Job.id == job_id).first()
    if not job:
        print(f"Report job {job_id} not found while marking failed.", flush=True)
        return

    job.status = "failed"
    job.error_message = message
    job.completed_at = datetime.now(timezone.utc)
    db.add(job)
    db.commit()


def write_inventory_report(job_id: int) -> str:
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    report_path = REPORTS_DIR / f"inventory_report_job_{job_id}.txt"
    generated_at = datetime.now(timezone.utc).isoformat()
    report_path.write_text(
        "\n".join([
            "SecureOps Inventory Report",
            f"Job ID: {job_id}",
            f"Generated at: {generated_at}",
            "Status: completed",
            "Note: This is a simulated background report generated by worker-service.",
            "",
        ]),
        encoding="utf-8",
    )
    return str(report_path)


def write_low_stock_report(db: Session, job_id: int) -> str:
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    report_path = REPORTS_DIR / f"low_stock_report_job_{job_id}.txt"
    generated_at = datetime.now(timezone.utc).isoformat()
    products = db.execute(
        text(
            """
            SELECT id, name, sku, category, quantity
            FROM products
            WHERE quantity <= 5
            ORDER BY quantity ASC, name ASC
            """
        )
    ).mappings().all()

    lines = [
        "SecureOps Low Stock Report",
        f"Job ID: {job_id}",
        f"Generated at: {generated_at}",
        "Status: completed",
        "Low stock threshold: quantity <= 5",
        "Note: This report highlights products that need restocking.",
        "",
    ]

    if products:
        lines.append("Products:")
        for product in products:
            lines.append(
                f"- #{product['id']} {product['name']} ({product['sku']}) | "
                f"{product['category']} | quantity: {product['quantity']}"
            )
    else:
        lines.append("No low stock products found.")

    lines.append("")
    report_path.write_text("\n".join(lines), encoding="utf-8")
    return str(report_path)


def process_report_job(payload: dict[str, Any]) -> None:
    job_id = int(payload["job_id"])
    job_type = payload["type"]

    with SessionLocal() as db:
        job = db.query(Job).filter(Job.id == job_id).first()
        if not job:
            raise ValueError(f"Report job {job_id} was not found.")

        job.status = "processing"
        job.error_message = None
        db.add(job)
        db.commit()
        send_audit_event(
            "reports.job.processing",
            "worker-service",
            "info",
            user_id=job.requested_by,
            details={"job_id": job.id, "type": job.type},
        )

        try:
            time.sleep(2)
            if job_type == "inventory_report":
                result_path = write_inventory_report(job_id)
            elif job_type == "low_stock_report":
                result_path = write_low_stock_report(db, job_id)
            else:
                raise ValueError("Unsupported report job type.")
            job.status = "completed"
            job.result_path = result_path
            job.completed_at = datetime.now(timezone.utc)
            db.add(job)
            db.commit()
            send_audit_event(
                "reports.job.completed",
                "worker-service",
                "success",
                user_id=job.requested_by,
                details={"job_id": job.id, "type": job.type, "result_path": result_path},
            )
            print(f"Completed report job {job_id}.", flush=True)
        except Exception as exc:
            db.rollback()
            set_job_failed(db, job_id, "Report generation failed.")
            send_audit_event(
                "reports.job.failed",
                "worker-service",
                "failure",
                user_id=job.requested_by,
                details={"job_id": job_id, "type": job_type},
            )
            raise RuntimeError(f"Report job {job_id} failed.") from exc


def handle_message(
    channel: pika.adapters.blocking_connection.BlockingChannel,
    method: pika.spec.Basic.Deliver,
    _properties: pika.BasicProperties,
    body: bytes,
) -> None:
    job_id: int | None = None
    try:
        payload = load_message(body)
        job_id = int(payload["job_id"])
        process_report_job(payload)
    except Exception as exc:
        print(f"Report job failed: {exc}", flush=True)
        if job_id is not None:
            with SessionLocal() as db:
                set_job_failed(db, job_id, "Report generation failed.")
            send_audit_event(
                "reports.job.failed",
                "worker-service",
                "failure",
                details={"job_id": job_id},
            )
    finally:
        channel.basic_ack(delivery_tag=method.delivery_tag)


def main() -> None:
    Base.metadata.create_all(bind=engine)
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)

    while True:
        connection: pika.BlockingConnection | None = None
        try:
            connection = connect_with_retry()
            channel = connection.channel()
            channel.queue_declare(queue=QUEUE_NAME, durable=True)
            channel.basic_qos(prefetch_count=1)
            channel.basic_consume(queue=QUEUE_NAME, on_message_callback=handle_message)
            print("Worker connected to RabbitMQ and waiting for report jobs.", flush=True)
            channel.start_consuming()
        except KeyboardInterrupt:
            print("Worker shutting down", flush=True)
            if connection and connection.is_open:
                connection.close()
            break
        except Exception as exc:
            print(f"Worker connection error: {exc}", flush=True)
            if connection and connection.is_open:
                connection.close()
            time.sleep(5)


if __name__ == "__main__":
    main()
